{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Jupyter environment detected. Enabling Open3D WebVisualizer.\n",
      "[Open3D INFO] WebRTC GUI backend enabled.\n",
      "[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import open3d as o3d\n",
    "import copy\n",
    "import pickle\n",
    "from tqdm import tqdm\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from scipy.spatial import cKDTree\n",
    "from matplotlib.colors import LinearSegmentedColormap\n",
    "\n",
    "from OCC.Core.STEPControl import STEPControl_Reader\n",
    "from OCC.Core.IFSelect import IFSelect_RetDone\n",
    "from OCC.Core.TopAbs import TopAbs_WIRE, TopAbs_EDGE, TopAbs_VERTEX\n",
    "from OCC.Core.TopExp import TopExp_Explorer\n",
    "from OCC.Core.TopoDS import topods\n",
    "from OCC.Core.BRep import BRep_Tool\n",
    "from OCC.Core.BRepAdaptor import BRepAdaptor_Curve\n",
    "from OCC.Core.GeomAbs import GeomAbs_Circle, GeomAbs_Ellipse, GeomAbs_Line, GeomAbs_BSplineCurve, GeomAbs_Hyperbola, GeomAbs_Parabola\n",
    "from OCC.Core.TopAbs import TopAbs_WIRE, TopAbs_EDGE, TopAbs_VERTEX\n",
    "from OCC.Display.SimpleGui import init_display\n",
    "from OCC.Core.BRepOffsetAPI import BRepOffsetAPI_MakeOffset\n",
    "from OCC.Core.Quantity import Quantity_Color, Quantity_TOC_RGB\n",
    "from OCC.Core.gp import gp_Pnt\n",
    "from OCC.Core.BRepBuilderAPI import BRepBuilderAPI_MakeVertex\n",
    "from PyQt5 import QtWidgets\n",
    "from OCC.Core.GCPnts import GCPnts_UniformDeflection\n",
    "from OCC.Core.GProp import GProp_GProps\n",
    "from OCC.Core.BRepGProp import brepgprop\n",
    "from scipy.spatial import ConvexHull"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Step file has been loaded successfully.\n"
     ]
    }
   ],
   "source": [
    "# Read cad model data (STEP file)\n",
    "width = 0.5\n",
    "\n",
    "step_file_path = '/home/chris/Code/PointClouds/data/other_files/MortenPartSTEPVersion.STEP'\n",
    "\n",
    "def load_step_file(file_path):\n",
    "    step_reader = STEPControl_Reader()\n",
    "    status = step_reader.ReadFile(file_path)\n",
    "    if status == IFSelect_RetDone:\n",
    "        step_reader.TransferRoots()\n",
    "        shape = step_reader.OneShape()\n",
    "        return shape\n",
    "    else:\n",
    "        raise Exception(\"Error: Cannot read STEP file.\")\n",
    "\n",
    "shape = load_step_file(step_file_path)\n",
    "\n",
    "print('Step file has been loaded successfully.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Generating top view edges and sampling to create the associated point cloud...\n",
      "Total number of top view edges: 586\n",
      "Total number of points in the cad point cloud: 81774\n",
      "Top view cad point cloud created.\n"
     ]
    }
   ],
   "source": [
    "def extract_top_edges(shape, deflection=0.1):\n",
    "    edges = []\n",
    "    max_z = -float('inf')\n",
    "    edge_z_coordinates = []\n",
    "\n",
    "    # First pass to collect the highest Z-coordinate of each edge\n",
    "    exp_edge = TopExp_Explorer(shape, TopAbs_EDGE)\n",
    "    while exp_edge.More():\n",
    "        edge = topods.Edge(exp_edge.Current())\n",
    "        edge_max_z = -float('inf')\n",
    "        exp_vertex = TopExp_Explorer(edge, TopAbs_VERTEX)\n",
    "        vertices = []\n",
    "        while exp_vertex.More():\n",
    "            vertex = topods.Vertex(exp_vertex.Current())\n",
    "            point = BRep_Tool.Pnt(vertex)\n",
    "            vertices.append(point)\n",
    "            if point.Z() > edge_max_z:\n",
    "                edge_max_z = point.Z()\n",
    "            exp_vertex.Next()\n",
    "        edge_z_coordinates.append((edge, edge_max_z, vertices))\n",
    "        if edge_max_z > max_z:\n",
    "            max_z = edge_max_z\n",
    "        exp_edge.Next()\n",
    "\n",
    "    #print(f\"Total number of edges: {len(edge_z_coordinates)}\")\n",
    "    #print(f\"Maximum Z-coordinate found: {max_z}\")\n",
    "\n",
    "    # Collect edges on the top plane\n",
    "    top_edges = []\n",
    "    point_cloud = []\n",
    "    for edge, z, vertices in edge_z_coordinates:\n",
    "        if all(abs(vertex.Z() - max_z) < 1e-3 for vertex in vertices):  # Ensure all vertices are at the top surface\n",
    "            top_edges.append(edge)\n",
    "            #print(f\"Top edge added with highest vertex Z: {z}\")\n",
    "\n",
    "            # Sample points along the edge\n",
    "            curve = BRepAdaptor_Curve(edge)\n",
    "            u_min, u_max = curve.FirstParameter(), curve.LastParameter()\n",
    "\n",
    "            # Calculate the length of the edge\n",
    "            linear_props = GProp_GProps()\n",
    "            brepgprop.LinearProperties(edge, linear_props)\n",
    "            length = linear_props.Mass()\n",
    "\n",
    "            # Calculate the number of samples based on the length and the desired point density\n",
    "            num_samples = int(length / deflection)\n",
    "\n",
    "            for i in range(num_samples):\n",
    "                u = u_min + i * (u_max - u_min) / (num_samples - 1)\n",
    "                pnt = curve.Value(u)\n",
    "                point_cloud.append((pnt.X(), pnt.Y(), pnt.Z()))  # Store the coordinates as a tuple\n",
    "\n",
    "    print(f\"Total number of top view edges: {len(top_edges)}\")\n",
    "    print(f\"Total number of points in the cad point cloud: {len(point_cloud)}\")\n",
    "    return top_edges, point_cloud\n",
    "\n",
    "# Visualize the top edges\n",
    "def visualize_top_edges(top_edges):\n",
    "    display, start_display, add_menu, add_function_to_menu = init_display()\n",
    "\n",
    "    # Assign the color red to each top edge\n",
    "    red_color = Quantity_Color(1.0, 0.0, 0.0, Quantity_TOC_RGB)\n",
    "    \n",
    "    # Display each top edge with the red color\n",
    "    for edge in top_edges:\n",
    "        display.DisplayShape(edge, update=True, color=red_color)\n",
    "\n",
    "    start_display()\n",
    "\n",
    "\n",
    "# Main execution\n",
    "print('Generating top view edges and sampling to create the associated point cloud...')\n",
    "top_edges, cad_points = extract_top_edges(shape)\n",
    "# if top_edges:\n",
    "#     visualize_top_edges(top_edges)\n",
    "# else:\n",
    "#     print(\"Top edges not found.\")\n",
    "\n",
    "cad_pcd = o3d.geometry.PointCloud()\n",
    "cad_pcd.points = o3d.utility.Vector3dVector(np.asarray(cad_points))\n",
    "o3d.visualization.draw_geometries([cad_pcd])\n",
    "\n",
    "print('Top view cad point cloud created.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Precompute neighbors.[========================================] 100%\n",
      "Clustering[========================================] 100%\n",
      "Cad point cloud has 79 clusters\n"
     ]
    }
   ],
   "source": [
    "# Apply clustering to the cad_pcd\n",
    "\n",
    "eps = 0.50\n",
    "min_points = 10\n",
    "\n",
    "cad_shapes_labels = np.array(cad_pcd.cluster_dbscan(eps=eps, min_points=min_points, print_progress=True))\n",
    "\n",
    "max_label = cad_shapes_labels.max()\n",
    "print(f\"Cad point cloud has {max_label + 1} clusters\")\n",
    "base_cmap = plt.get_cmap(\"tab20\")\n",
    "color_cycle = [base_cmap(i % 20) for i in range(max_label + 1)]\n",
    "colors = np.array(color_cycle)[cad_shapes_labels]\n",
    "colors[cad_shapes_labels<0] = 0\n",
    "cad_pcd.colors = o3d.utility.Vector3dVector(colors[:, :3])\n",
    "\n",
    "cad_points_dictionary = {}\n",
    "cad_centers_dictionary = {}\n",
    "\n",
    "# Extract the points and calculate the centers for each cluster\n",
    "for label in np.unique(cad_shapes_labels):\n",
    "    if label != -1:  # Ignore noise\n",
    "        cluster_points = np.asarray(cad_pcd.points)[cad_shapes_labels == label]\n",
    "        cad_points_dictionary[label] = cluster_points\n",
    "        cad_centers_dictionary[label] = np.mean(cluster_points, axis=0)\n",
    "\n",
    "cad_centers_pcd = o3d.geometry.PointCloud()\n",
    "cad_centers_points = list(cad_centers_dictionary.values())\n",
    "cad_centers_pcd.points = o3d.utility.Vector3dVector(np.array(cad_centers_points))\n",
    "cad_centers_pcd.paint_uniform_color([0, 1, 0])  # Color centers blue\n",
    "\n",
    "o3d.visualization.draw_geometries([cad_pcd])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_979961/3606754200.py:18: DeprecationWarning: Please import `QhullError` from the `scipy.spatial` namespace; the `scipy.spatial.qhull` namespace is deprecated and will be removed in SciPy 2.0.0.\n",
      "  except (scipy.spatial.qhull.QhullError, ValueError):\n"
     ]
    }
   ],
   "source": [
    "import scipy\n",
    "from scipy.spatial import ConvexHull, Delaunay\n",
    "\n",
    "def find_interior_point(points):\n",
    "    \"\"\"\n",
    "    Find an interior point of the shape using the convex hull.\n",
    "    \n",
    "    Args:\n",
    "    - points (numpy.ndarray): The points of the shape.\n",
    "    \n",
    "    Returns:\n",
    "    - numpy.ndarray: An interior point of the shape.\n",
    "    \"\"\"\n",
    "    try:\n",
    "        hull = ConvexHull(points)\n",
    "        hull_points = points[hull.vertices]\n",
    "        interior_point = np.mean(hull_points, axis=0)\n",
    "    except (scipy.spatial.qhull.QhullError, ValueError):\n",
    "        # Fall back to the centroid if the convex hull fails\n",
    "        interior_point = np.mean(points, axis=0)\n",
    "    return interior_point\n",
    "\n",
    "def magnify_shape(points, interior_point, distance):\n",
    "    \"\"\"\n",
    "    Magnify the shape by moving each point away from the interior point.\n",
    "    \n",
    "    Args:\n",
    "    - points (numpy.ndarray): The points of the shape.\n",
    "    - interior_point (numpy.ndarray): The interior point of the shape.\n",
    "    - distance (float): The distance by which to magnify the shape.\n",
    "    \n",
    "    Returns:\n",
    "    - numpy.ndarray: The magnified points.\n",
    "    \"\"\"\n",
    "    vectors = points - interior_point\n",
    "    magnified_points = points + (vectors / np.linalg.norm(vectors, axis=1, keepdims=True)) * distance\n",
    "    return magnified_points\n",
    "\n",
    "# Example usage with your cad_points_dictionary\n",
    "scale_factor = 1.5  # Define your scale factor here\n",
    "\n",
    "magnified_points_dict = {}\n",
    "for label, points in cad_points_dictionary.items():\n",
    "    interior_point = find_interior_point(points)\n",
    "    magnified_points = magnify_shape(points, interior_point, scale_factor)\n",
    "    magnified_points_dict[label] = magnified_points\n",
    "\n",
    "# Convert the original and magnified points back to a combined point cloud for visualization\n",
    "all_original_points = np.vstack(list(cad_points_dictionary.values()))\n",
    "all_magnified_points = np.vstack(list(magnified_points_dict.values()))\n",
    "\n",
    "combined_points = np.vstack((all_original_points, all_magnified_points))\n",
    "\n",
    "combined_pcd = o3d.geometry.PointCloud()\n",
    "combined_pcd.points = o3d.utility.Vector3dVector(combined_points)\n",
    "\n",
    "# Assign different colors to original and magnified points for better visualization\n",
    "original_colors = np.tile([0, 0, 1], (all_original_points.shape[0], 1))  # Blue for original points\n",
    "magnified_colors = np.tile([1, 0, 0], (all_magnified_points.shape[0], 1))  # Red for magnified points\n",
    "\n",
    "combined_colors = np.vstack((original_colors, magnified_colors))\n",
    "combined_pcd.colors = o3d.utility.Vector3dVector(combined_colors)\n",
    "\n",
    "# Visualize the combined shapes\n",
    "o3d.visualization.draw_geometries([combined_pcd])\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "pointclouds",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
