{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import open3d as o3d\n",
    "import copy\n",
    "import pickle\n",
    "from tqdm import tqdm\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import time\n",
    "from scipy.spatial import cKDTree\n",
    "from joblib import Parallel, delayed\n",
    "\n",
    "from OCC.Core.STEPControl import STEPControl_Reader\n",
    "from OCC.Core.IFSelect import IFSelect_RetDone\n",
    "from OCC.Core.TopAbs import TopAbs_WIRE, TopAbs_EDGE, TopAbs_VERTEX\n",
    "from OCC.Core.TopExp import TopExp_Explorer\n",
    "from OCC.Core.TopoDS import topods\n",
    "from OCC.Core.BRep import BRep_Tool\n",
    "from OCC.Core.BRepAdaptor import BRepAdaptor_Curve\n",
    "from OCC.Core.GeomAbs import GeomAbs_Circle, GeomAbs_Ellipse, GeomAbs_Line, GeomAbs_BSplineCurve, GeomAbs_Hyperbola, GeomAbs_Parabola\n",
    "from OCC.Core.TopAbs import TopAbs_WIRE, TopAbs_EDGE, TopAbs_VERTEX\n",
    "from OCC.Display.SimpleGui import init_display\n",
    "from OCC.Core.Quantity import Quantity_Color, Quantity_TOC_RGB\n",
    "from OCC.Core.gp import gp_Pnt\n",
    "from OCC.Core.BRepBuilderAPI import BRepBuilderAPI_MakeVertex\n",
    "from PyQt5 import QtWidgets\n",
    "from OCC.Core.GCPnts import GCPnts_UniformDeflection\n",
    "from OCC.Core.GProp import GProp_GProps\n",
    "from OCC.Core.BRepGProp import brepgprop"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Read processed point cloud data\n",
    "\n",
    "point_dictionary_path = '/home/chris/Code/PointClouds/data/hull_pcd/morten_plate/mapped_hull_points_dictionary.pkl'\n",
    "\n",
    "hull_centers_dictionary = {}\n",
    "\n",
    "with open(point_dictionary_path, 'rb') as f:\n",
    "    hull_points_dictionary = pickle.load(f)\n",
    "\n",
    "hull_pcd = o3d.geometry.PointCloud()\n",
    "\n",
    "for label, points in hull_points_dictionary.items():\n",
    "    hull_pcd.points.extend(o3d.utility.Vector3dVector(points))\n",
    "    center = np.mean(points, axis=0)\n",
    "    hull_centers_dictionary[label] = center\n",
    "    \n",
    "hull_pcd.paint_uniform_color([0.1, 1, 0.1])\n",
    "\n",
    "hull_centers_pcd = o3d.geometry.PointCloud()\n",
    "hull_centers_points = list(hull_centers_dictionary.values())\n",
    "hull_centers_pcd.points = o3d.utility.Vector3dVector(np.array(hull_centers_points))\n",
    "hull_centers_pcd.paint_uniform_color([1, 0, 0])  # Color centers red\n",
    "\n",
    "print(\"Point cloud data has been loaded successfully.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Read cad model data (STEP file)\n",
    "\n",
    "step_file_path = '/home/chris/Code/PointClouds/data/other_files/MortenPartSTEPVersion.STEP'\n",
    "\n",
    "def load_step_file(file_path):\n",
    "    step_reader = STEPControl_Reader()\n",
    "    status = step_reader.ReadFile(file_path)\n",
    "    if status == IFSelect_RetDone:\n",
    "        step_reader.TransferRoots()\n",
    "        shape = step_reader.OneShape()\n",
    "        return shape\n",
    "    else:\n",
    "        raise Exception(\"Error: Cannot read STEP file.\")\n",
    "\n",
    "shape = load_step_file(step_file_path)\n",
    "\n",
    "print('Step file has been loaded successfully.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Extract edges at the top Z-coordinate\n",
    "def extract_top_edges(shape, deflection=0.1):\n",
    "    edges = []\n",
    "    max_z = -float('inf')\n",
    "    edge_z_coordinates = []\n",
    "\n",
    "    # First pass to collect the highest Z-coordinate of each edge\n",
    "    exp_edge = TopExp_Explorer(shape, TopAbs_EDGE)\n",
    "    while exp_edge.More():\n",
    "        edge = topods.Edge(exp_edge.Current())\n",
    "        edge_max_z = -float('inf')\n",
    "        exp_vertex = TopExp_Explorer(edge, TopAbs_VERTEX)\n",
    "        vertices = []\n",
    "        while exp_vertex.More():\n",
    "            vertex = topods.Vertex(exp_vertex.Current())\n",
    "            point = BRep_Tool.Pnt(vertex)\n",
    "            vertices.append(point)\n",
    "            if point.Z() > edge_max_z:\n",
    "                edge_max_z = point.Z()\n",
    "            exp_vertex.Next()\n",
    "        edge_z_coordinates.append((edge, edge_max_z, vertices))\n",
    "        if edge_max_z > max_z:\n",
    "            max_z = edge_max_z\n",
    "        exp_edge.Next()\n",
    "\n",
    "    #print(f\"Total number of edges: {len(edge_z_coordinates)}\")\n",
    "    #print(f\"Maximum Z-coordinate found: {max_z}\")\n",
    "\n",
    "    # Collect edges on the top plane\n",
    "    top_edges = []\n",
    "    point_cloud = []\n",
    "    for edge, z, vertices in edge_z_coordinates:\n",
    "        if all(abs(vertex.Z() - max_z) < 1e-3 for vertex in vertices):  # Ensure all vertices are at the top surface\n",
    "            top_edges.append(edge)\n",
    "            #print(f\"Top edge added with highest vertex Z: {z}\")\n",
    "\n",
    "            # Sample points along the edge\n",
    "            curve = BRepAdaptor_Curve(edge)\n",
    "            u_min, u_max = curve.FirstParameter(), curve.LastParameter()\n",
    "\n",
    "            # Calculate the length of the edge\n",
    "            linear_props = GProp_GProps()\n",
    "            brepgprop.LinearProperties(edge, linear_props)\n",
    "            length = linear_props.Mass()\n",
    "\n",
    "            # Calculate the number of samples based on the length and the desired point density\n",
    "            num_samples = int(length / deflection)\n",
    "\n",
    "            for i in range(num_samples):\n",
    "                u = u_min + i * (u_max - u_min) / (num_samples - 1)\n",
    "                pnt = curve.Value(u)\n",
    "                point_cloud.append((pnt.X(), pnt.Y(), pnt.Z()))  # Store the coordinates as a tuple\n",
    "\n",
    "    print(f\"Total number of top view edges: {len(top_edges)}\")\n",
    "    print(f\"Total number of points in the cad point cloud: {len(point_cloud)}\")\n",
    "    return top_edges, point_cloud\n",
    "\n",
    "# Visualize the top edges\n",
    "def visualize_top_edges(top_edges):\n",
    "    display, start_display, add_menu, add_function_to_menu = init_display()\n",
    "\n",
    "    # Assign the color red to each top edge\n",
    "    red_color = Quantity_Color(1.0, 0.0, 0.0, Quantity_TOC_RGB)\n",
    "    \n",
    "    # Display each top edge with the red color\n",
    "    for edge in top_edges:\n",
    "        display.DisplayShape(edge, update=True, color=red_color)\n",
    "\n",
    "    start_display()\n",
    "\n",
    "\n",
    "# Main execution\n",
    "print('Generating top view edges and sampling to create the associated point cloud...')\n",
    "top_edges, cad_points = extract_top_edges(shape)\n",
    "# if top_edges:\n",
    "#     visualize_top_edges(top_edges)\n",
    "# else:\n",
    "#     print(\"Top edges not found.\")\n",
    "\n",
    "cad_pcd = o3d.geometry.PointCloud()\n",
    "cad_pcd.points = o3d.utility.Vector3dVector(np.asarray(cad_points))\n",
    "o3d.visualization.draw_geometries([cad_pcd])\n",
    "\n",
    "print('Top view cad point cloud created.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Apply clustering to the cad_pcd\n",
    "\n",
    "eps = 0.50\n",
    "min_points = 10\n",
    "\n",
    "cad_shapes_labels = np.array(cad_pcd.cluster_dbscan(eps=eps, min_points=min_points, print_progress=True))\n",
    "\n",
    "max_label = cad_shapes_labels.max()\n",
    "print(f\"Cad point cloud has {max_label + 1} clusters\")\n",
    "base_cmap = plt.get_cmap(\"tab20\")\n",
    "color_cycle = [base_cmap(i % 20) for i in range(max_label + 1)]\n",
    "colors = np.array(color_cycle)[cad_shapes_labels]\n",
    "colors[cad_shapes_labels<0] = 0\n",
    "cad_pcd.colors = o3d.utility.Vector3dVector(colors[:, :3])\n",
    "\n",
    "cad_points_dictionary = {}\n",
    "cad_centers_dictionary = {}\n",
    "\n",
    "# Extract the points and calculate the centers for each cluster\n",
    "for label in np.unique(cad_shapes_labels):\n",
    "    if label != -1:  # Ignore noise\n",
    "        cluster_points = np.asarray(cad_pcd.points)[cad_shapes_labels == label]\n",
    "        cad_points_dictionary[label] = cluster_points\n",
    "        cad_centers_dictionary[label] = np.mean(cluster_points, axis=0)\n",
    "\n",
    "cad_centers_pcd = o3d.geometry.PointCloud()\n",
    "cad_centers_points = list(cad_centers_dictionary.values())\n",
    "cad_centers_pcd.points = o3d.utility.Vector3dVector(np.array(cad_centers_points))\n",
    "cad_centers_pcd.paint_uniform_color([0, 1, 0])  # Color centers blue\n",
    "\n",
    "o3d.visualization.draw_geometries([cad_pcd])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#Center based alignment: Align point clouds through ICP based on the lowest RMSE (only use centers of shapes)\n",
    "\n",
    "cad_centers_pcd_center = np.mean(np.asarray(cad_centers_pcd.points), axis=0)\n",
    "hull_centers_pcd_center = np.mean(np.asarray(hull_centers_pcd.points), axis=0)\n",
    "\n",
    "# Compute the translation vector\n",
    "translation = cad_centers_pcd_center - hull_centers_pcd_center\n",
    "\n",
    "# Translate the hull_pcd to align the centers\n",
    "hull_centers_pcd.points = o3d.utility.Vector3dVector(np.asarray(hull_centers_pcd.points) + translation)\n",
    "hull_pcd.points = o3d.utility.Vector3dVector(np.asarray(hull_pcd.points) + translation)\n",
    "\n",
    "o3d.visualization.draw_geometries([cad_centers_pcd, hull_centers_pcd])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "cad_centers_points = np.asarray(cad_centers_pcd.points)[:, :2]\n",
    "hull_centers_points = np.asarray(hull_centers_pcd.points)[:, :2]\n",
    "\n",
    "def get_rotation_matrix(angle):\n",
    "    return np.array([[np.cos(angle), -np.sin(angle)], [np.sin(angle), np.cos(angle)]])\n",
    "\n",
    "def apply_rotation(centered_clouds, angle):\n",
    "    rotation_matrix = get_rotation_matrix(angle)\n",
    "    rotated_clouds = np.einsum('ij,nkj->nki', rotation_matrix, centered_clouds)\n",
    "    return rotated_clouds\n",
    "\n",
    "def calculate_distances_optimized(rotated_clouds, cloud_B):\n",
    "    tree = cKDTree(cloud_B)\n",
    "    distances, _ = tree.query(rotated_clouds.reshape(-1, 2))\n",
    "    return distances.reshape(rotated_clouds.shape[0], rotated_clouds.shape[1])\n",
    "\n",
    "def process_angle(angle, centered_clouds, cloud_B, centering_vectors):\n",
    "    rotated_clouds = apply_rotation(centered_clouds, angle)\n",
    "    uncentered_rotated_clouds = rotated_clouds + centering_vectors[:, np.newaxis, :]\n",
    "    distances = calculate_distances_optimized(uncentered_rotated_clouds, cloud_B)\n",
    "    avg_shortest_distances = np.mean(distances, axis=1)\n",
    "    min_distance_idx = np.argmin(avg_shortest_distances)\n",
    "    return avg_shortest_distances[min_distance_idx], angle, min_distance_idx\n",
    "\n",
    "def ransac_match_clouds(cloud_A, cloud_B):\n",
    "    print(cloud_A.shape)\n",
    "    print(cloud_B.shape)\n",
    "    best_transformation = None\n",
    "    min_avg_distance = float('inf')\n",
    "    angles = np.arange(-np.pi, np.pi, np.pi/720)\n",
    "\n",
    "    cloud_A_indices = np.arange(cloud_A.shape[0])\n",
    "    cloud_B_indices = np.arange(cloud_B.shape[0])\n",
    "    combinations = np.array(np.meshgrid(cloud_A_indices, cloud_B_indices)).T.reshape(-1, 2)\n",
    "    shuffled_combinations = np.random.permutation(combinations)\n",
    "    translations = cloud_B[shuffled_combinations[:, 1]] - cloud_A[shuffled_combinations[:, 0]]\n",
    "\n",
    "    #print(\"Translations shape:\", translations.shape)\n",
    "\n",
    "    translated_clouds = cloud_A[np.newaxis, :, :] + translations[:, np.newaxis, :]\n",
    "    centering_vectors = cloud_B[shuffled_combinations[:, 1]]\n",
    "    centered_clouds = translated_clouds - centering_vectors[:, np.newaxis, :]\n",
    "\n",
    "    #print(\"Centered clouds shape:\", centered_clouds.shape)\n",
    "\n",
    "    results = Parallel(n_jobs=-1)(delayed(process_angle)(angle, centered_clouds, cloud_B, centering_vectors) for angle in tqdm(angles))\n",
    "\n",
    "    for avg_distance, angle, idx in results:\n",
    "        if avg_distance < min_avg_distance:\n",
    "            min_avg_distance = avg_distance\n",
    "            best_rotation_matrix = get_rotation_matrix(angle)\n",
    "            best_translation_vector = translations[idx]\n",
    "            best_centering_vector = centering_vectors[idx]\n",
    "            best_transformation = np.eye(3)\n",
    "            best_rotation_matrix_aug = np.eye(3)\n",
    "            best_rotation_matrix_aug[:2, :2] = best_rotation_matrix\n",
    "            \n",
    "            # Augment the translation vectors to 3x3\n",
    "            T1 = np.eye(3)\n",
    "            T1[:2, 2] = best_translation_vector\n",
    "            \n",
    "            T2 = np.eye(3)\n",
    "            T2[:2, 2] = best_centering_vector\n",
    "            \n",
    "            T3 = np.eye(3)\n",
    "            T3[:2, 2] = -best_centering_vector\n",
    "            \n",
    "            # Combine the transformations\n",
    "            best_transformation = T1 @ T2 @ best_rotation_matrix_aug @ T3\n",
    "\n",
    "    #print(\"Best rotation matrix:\", best_rotation_matrix)\n",
    "    #print(\"Best translation vector:\", best_translation_vector)\n",
    "    print(\"Minimum average distance:\", min_avg_distance)\n",
    "\n",
    "    return best_transformation, min_avg_distance\n",
    "\n",
    "best_transformation, min_avg_distance = ransac_match_clouds(cad_centers_points, hull_centers_points)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "best_transformation_3d = np.eye(4)\n",
    "best_transformation_3d[:2, :2] = best_transformation[:2, :2]\n",
    "best_transformation_3d[:2, 3] = best_transformation[:2, 2]\n",
    "\n",
    "#print(\"Best 3D transformation matrix: \\n\", best_transformation_3d)\n",
    "\n",
    "# Apply the transformation to a copy of the hull_centers_pcd for visualization\n",
    "cad_centers_pcd_transformed = cad_centers_pcd.transform(best_transformation_3d)\n",
    "\n",
    "# Visualize the final aligned point clouds\n",
    "o3d.visualization.draw_geometries([hull_centers_pcd, cad_centers_pcd_transformed])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "best_transformation_3d = np.eye(4)\n",
    "best_transformation_3d[:2, :2] = best_transformation[:2, :2]\n",
    "best_transformation_3d[:2, 3] = best_transformation[:2, 2]\n",
    "\n",
    "#print(\"Best 3D transformation matrix: \\n\", best_transformation_3d)\n",
    "\n",
    "# Apply the transformation to a copy of the hull_centers_pcd for visualization\n",
    "cad_pcd_transformed = cad_pcd.transform(best_transformation_3d)\n",
    "\n",
    "# Visualize the final aligned point clouds\n",
    "o3d.visualization.draw_geometries([hull_pcd, cad_pcd_transformed])"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "pointclouds",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.11.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
