{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import open3d as o3d\n",
    "import copy\n",
    "import pickle\n",
    "from tqdm import tqdm\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from scipy.spatial import cKDTree\n",
    "from matplotlib.colors import LinearSegmentedColormap\n",
    "\n",
    "from OCC.Core.STEPControl import STEPControl_Reader\n",
    "from OCC.Core.IFSelect import IFSelect_RetDone\n",
    "from OCC.Core.TopAbs import TopAbs_WIRE, TopAbs_EDGE, TopAbs_VERTEX\n",
    "from OCC.Core.TopExp import TopExp_Explorer\n",
    "from OCC.Core.TopoDS import topods\n",
    "from OCC.Core.BRep import BRep_Tool\n",
    "from OCC.Core.BRepAdaptor import BRepAdaptor_Curve\n",
    "from OCC.Core.GeomAbs import GeomAbs_Circle, GeomAbs_Ellipse, GeomAbs_Line, GeomAbs_BSplineCurve, GeomAbs_Hyperbola, GeomAbs_Parabola\n",
    "from OCC.Core.TopAbs import TopAbs_WIRE, TopAbs_EDGE, TopAbs_VERTEX\n",
    "from OCC.Display.SimpleGui import init_display\n",
    "from OCC.Core.Quantity import Quantity_Color, Quantity_TOC_RGB\n",
    "from OCC.Core.gp import gp_Pnt\n",
    "from OCC.Core.BRepBuilderAPI import BRepBuilderAPI_MakeVertex\n",
    "from PyQt5 import QtWidgets\n",
    "from OCC.Core.GCPnts import GCPnts_UniformDeflection\n",
    "from OCC.Core.GProp import GProp_GProps\n",
    "from OCC.Core.BRepGProp import brepgprop"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Point cloud data has been loaded successfully.\n"
     ]
    }
   ],
   "source": [
    "# Read processed point cloud data\n",
    "\n",
    "point_dictionary_path = '/home/chris/Code/PointClouds/data/hull_pcd/morten_plate/mapped_hull_points_dictionary.pkl'\n",
    "\n",
    "hull_centers_dictionary = {}\n",
    "\n",
    "with open(point_dictionary_path, 'rb') as f:\n",
    "    hull_points_dictionary = pickle.load(f)\n",
    "\n",
    "hull_pcd = o3d.geometry.PointCloud()\n",
    "\n",
    "for label, points in hull_points_dictionary.items():\n",
    "    hull_pcd.points.extend(o3d.utility.Vector3dVector(points))\n",
    "    center = np.mean(points, axis=0)\n",
    "    hull_centers_dictionary[label] = center\n",
    "    \n",
    "hull_pcd.paint_uniform_color([0.1, 1, 0.1])\n",
    "\n",
    "hull_centers_pcd = o3d.geometry.PointCloud()\n",
    "hull_centers_points = list(hull_centers_dictionary.values())\n",
    "hull_centers_pcd.points = o3d.utility.Vector3dVector(np.array(hull_centers_points))\n",
    "hull_centers_pcd.paint_uniform_color([1, 0, 0])  # Color centers red\n",
    "\n",
    "print(\"Point cloud data has been loaded successfully.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Step file has been loaded successfully.\n"
     ]
    }
   ],
   "source": [
    "# Read cad model data (STEP file)\n",
    "\n",
    "step_file_path = '/home/chris/Code/PointClouds/data/other_files/MortenPartSTEPVersion.STEP'\n",
    "\n",
    "def load_step_file(file_path):\n",
    "    step_reader = STEPControl_Reader()\n",
    "    status = step_reader.ReadFile(file_path)\n",
    "    if status == IFSelect_RetDone:\n",
    "        step_reader.TransferRoots()\n",
    "        shape = step_reader.OneShape()\n",
    "        return shape\n",
    "    else:\n",
    "        raise Exception(\"Error: Cannot read STEP file.\")\n",
    "\n",
    "shape = load_step_file(step_file_path)\n",
    "\n",
    "print('Step file has been loaded successfully.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Generating top view edges and sampling to create the associated point cloud...\n",
      "Total number of top view edges: 586\n",
      "Total number of points in the cad point cloud: 81774\n",
      "Top view cad point cloud created.\n"
     ]
    }
   ],
   "source": [
    "# Extract edges at the top Z-coordinate\n",
    "\n",
    "def extract_top_edges(shape, deflection=0.1):\n",
    "    edges = []\n",
    "    max_z = -float('inf')\n",
    "    edge_z_coordinates = []\n",
    "\n",
    "    # First pass to collect the highest Z-coordinate of each edge\n",
    "    exp_edge = TopExp_Explorer(shape, TopAbs_EDGE)\n",
    "    while exp_edge.More():\n",
    "        edge = topods.Edge(exp_edge.Current())\n",
    "        edge_max_z = -float('inf')\n",
    "        exp_vertex = TopExp_Explorer(edge, TopAbs_VERTEX)\n",
    "        vertices = []\n",
    "        while exp_vertex.More():\n",
    "            vertex = topods.Vertex(exp_vertex.Current())\n",
    "            point = BRep_Tool.Pnt(vertex)\n",
    "            vertices.append(point)\n",
    "            if point.Z() > edge_max_z:\n",
    "                edge_max_z = point.Z()\n",
    "            exp_vertex.Next()\n",
    "        edge_z_coordinates.append((edge, edge_max_z, vertices))\n",
    "        if edge_max_z > max_z:\n",
    "            max_z = edge_max_z\n",
    "        exp_edge.Next()\n",
    "\n",
    "    #print(f\"Total number of edges: {len(edge_z_coordinates)}\")\n",
    "    #print(f\"Maximum Z-coordinate found: {max_z}\")\n",
    "\n",
    "    # Collect edges on the top plane\n",
    "    top_edges = []\n",
    "    point_cloud = []\n",
    "    for edge, z, vertices in edge_z_coordinates:\n",
    "        if all(abs(vertex.Z() - max_z) < 1e-3 for vertex in vertices):  # Ensure all vertices are at the top surface\n",
    "            top_edges.append(edge)\n",
    "            #print(f\"Top edge added with highest vertex Z: {z}\")\n",
    "\n",
    "            # Sample points along the edge\n",
    "            curve = BRepAdaptor_Curve(edge)\n",
    "            u_min, u_max = curve.FirstParameter(), curve.LastParameter()\n",
    "\n",
    "            # Calculate the length of the edge\n",
    "            linear_props = GProp_GProps()\n",
    "            brepgprop.LinearProperties(edge, linear_props)\n",
    "            length = linear_props.Mass()\n",
    "\n",
    "            # Calculate the number of samples based on the length and the desired point density\n",
    "            num_samples = int(length / deflection)\n",
    "\n",
    "            for i in range(num_samples):\n",
    "                u = u_min + i * (u_max - u_min) / (num_samples - 1)\n",
    "                pnt = curve.Value(u)\n",
    "                point_cloud.append((pnt.X(), pnt.Y(), pnt.Z()))  # Store the coordinates as a tuple\n",
    "\n",
    "    print(f\"Total number of top view edges: {len(top_edges)}\")\n",
    "    print(f\"Total number of points in the cad point cloud: {len(point_cloud)}\")\n",
    "    return top_edges, point_cloud\n",
    "\n",
    "# Visualize the top edges\n",
    "def visualize_top_edges(top_edges):\n",
    "    display, start_display, add_menu, add_function_to_menu = init_display()\n",
    "\n",
    "    # Assign the color red to each top edge\n",
    "    red_color = Quantity_Color(1.0, 0.0, 0.0, Quantity_TOC_RGB)\n",
    "    \n",
    "    # Display each top edge with the red color\n",
    "    for edge in top_edges:\n",
    "        display.DisplayShape(edge, update=True, color=red_color)\n",
    "\n",
    "    start_display()\n",
    "\n",
    "\n",
    "# Main execution\n",
    "print('Generating top view edges and sampling to create the associated point cloud...')\n",
    "top_edges, cad_points = extract_top_edges(shape)\n",
    "# if top_edges:\n",
    "#     visualize_top_edges(top_edges)\n",
    "# else:\n",
    "#     print(\"Top edges not found.\")\n",
    "\n",
    "cad_pcd = o3d.geometry.PointCloud()\n",
    "cad_pcd.points = o3d.utility.Vector3dVector(np.asarray(cad_points))\n",
    "#o3d.visualization.draw_geometries([cad_pcd])\n",
    "\n",
    "print('Top view cad point cloud created.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "# # Apply clustering to the cad_pcd\n",
    "\n",
    "# eps = 0.50\n",
    "# min_points = 10\n",
    "\n",
    "# cad_shapes_labels = np.array(cad_pcd.cluster_dbscan(eps=eps, min_points=min_points, print_progress=True))\n",
    "\n",
    "# max_label = cad_shapes_labels.max()\n",
    "# print(f\"Cad point cloud has {max_label + 1} clusters\")\n",
    "# base_cmap = plt.get_cmap(\"tab20\")\n",
    "# color_cycle = [base_cmap(i % 20) for i in range(max_label + 1)]\n",
    "# colors = np.array(color_cycle)[cad_shapes_labels]\n",
    "# colors[cad_shapes_labels<0] = 0\n",
    "# cad_pcd.colors = o3d.utility.Vector3dVector(colors[:, :3])\n",
    "\n",
    "# cad_points_dictionary = {}\n",
    "# cad_centers_dictionary = {}\n",
    "\n",
    "# # Extract the points and calculate the centers for each cluster\n",
    "# for label in np.unique(cad_shapes_labels):\n",
    "#     if label != -1:  # Ignore noise\n",
    "#         cluster_points = np.asarray(cad_pcd.points)[cad_shapes_labels == label]\n",
    "#         cad_points_dictionary[label] = cluster_points\n",
    "#         cad_centers_dictionary[label] = np.mean(cluster_points, axis=0)\n",
    "\n",
    "# cad_centers_pcd = o3d.geometry.PointCloud()\n",
    "# cad_centers_points = list(cad_centers_dictionary.values())\n",
    "# cad_centers_pcd.points = o3d.utility.Vector3dVector(np.array(cad_centers_points))\n",
    "# cad_centers_pcd.paint_uniform_color([0, 1, 0])  # Color centers blue\n",
    "\n",
    "# #o3d.visualization.draw_geometries([cad_pcd])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "#VISUALIZE HERE\n",
    "o3d.visualization.draw_geometries([cad_pcd, hull_pcd])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#Align the centers of the two clouds for an initial alignment\n",
    "\n",
    "cad_pcd_center = np.mean(np.asarray(cad_pcd.points), axis=0)\n",
    "hull_pcd_center = np.mean(np.asarray(hull_pcd.points), axis=0)\n",
    "\n",
    "# Compute the translation vector\n",
    "translation = cad_pcd_center - hull_pcd_center\n",
    "\n",
    "# Translate the hull_pcd to align the centers\n",
    "hull_pcd.points = o3d.utility.Vector3dVector(np.asarray(hull_pcd.points) + translation)\n",
    "\n",
    "#o3d.visualization.draw_geometries([hull_pcd, cad_pcd])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "front =  [0.0, 0.0, 1.0]\n",
    "lookat = [-105.36407274754953, -106.22557127184305, 2.0]\n",
    "up =  [0.0, 1.0, 0.0]\n",
    "zoom = 0.69999999999999996\n",
    "\n",
    "def draw_registration_result(source, target, transformation):\n",
    "    source_temp = copy.deepcopy(source)\n",
    "    target_temp = copy.deepcopy(target)\n",
    "    source_temp.transform(transformation)\n",
    "    o3d.visualization.draw_geometries([target_temp, source_temp],\n",
    "                                      zoom=zoom,\n",
    "                                      front=front,\n",
    "                                      lookat=lookat,\n",
    "                                      up=up)\n",
    "    \n",
    "source = copy.deepcopy(hull_pcd)\n",
    "target = copy.deepcopy(cad_pcd)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Total points alignment: Align point clouds through ICP based on the lowest RMSE (use all points)\n",
    "\n",
    "def evaluate_icp(source, target, threshold, trans_init, verbose=False):\n",
    "    # Perform ICP registration\n",
    "    reg_p2p = o3d.pipelines.registration.registration_icp(\n",
    "        source, target, threshold, trans_init,\n",
    "        o3d.pipelines.registration.TransformationEstimationPointToPoint())\n",
    "    \n",
    "    # Evaluate the registration\n",
    "    evaluation = o3d.pipelines.registration.evaluate_registration(\n",
    "        source, target, threshold, reg_p2p.transformation)\n",
    "    \n",
    "    if verbose:\n",
    "        print(f\"Threshold: {threshold}\")\n",
    "        print(f\"Fitness: {reg_p2p.fitness}\")\n",
    "        print(f\"Inlier RMSE: {reg_p2p.inlier_rmse}\")\n",
    "        print(f\"Evaluation Fitness: {evaluation.fitness}\")\n",
    "        print(f\"Evaluation Inlier RMSE: {evaluation.inlier_rmse}\")\n",
    "        print(\"Transformation Matrix:\")\n",
    "        print(reg_p2p.transformation)\n",
    "        print(\"-\" * 40)\n",
    "    \n",
    "    return reg_p2p, evaluation.inlier_rmse, threshold\n",
    "\n",
    "# Initial transformation (identity matrix)\n",
    "trans_init = np.eye(4)\n",
    "\n",
    "# Evaluate ICP for different thresholds\n",
    "thresholds = [0.5, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6, 0.61, 0.62, 0.63, 0.64, 0.65, 0.67, 0.69, 0.7, 0.71, 0.72, 0.73, 0.8, 0.85, 0.9, 0.95, 1, 1.1, 1.2, 1.25, 1.3, 1,325, 1.33, 1.34, 1.35, 1.36, 1.37, 1.375, 1.4, 1.425, 1.45, 1.475, 1.5, 2, 3]\n",
    "results = [evaluate_icp(source, target, threshold, trans_init, verbose=False) for threshold in tqdm(thresholds)]\n",
    "best_result = min(results, key=lambda x: x[1])\n",
    "\n",
    "print(f'Best threshold for total alignment was {best_result[2]}')\n",
    "\n",
    "# Visual inspection for the best threshold \n",
    "draw_registration_result(source, target, best_result[0].transformation)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "pointclouds",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
